### ISSUE TITLE
[performance] comparison with ClickHouse latest version

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#1129]
*Summary*
```
... ...

Alexey Milovidov, [21.07.21 07:34]
Great! BTW, last night I tried to reproduce performance tests from your repository. I found that first queries are indeed faster in Datafuse (due to compilation for native instruction set) but the latest queries - the only queries with ORDER BY or GROUP BY are multiple times faster in ClickHouse. I've tested on Intel and AMD machines in AWS.

I can send you logs to update the results.

BohuTANG, [21.07.21 07:35]
Thanks. I will check it again

Alexey Milovidov, [21.07.21 07:36]
[ File : datafuse_log_intel.txt ]

Alexey Milovidov, [21.07.21 07:36]
[ File : datafuse_log_amd.txt ]

Alexey Milovidov, [21.07.21 07:37]
AMD machine is c5a.8xlarge.
Intel machine - don't remember, something like c5.8xlarge or similar.

BohuTANG, [21.07.21 07:38]
I will try the latest version ClickHouse
```

**Comment by sundy-li** [comment]
cc @alexey-milovidov

Hello, I just noticed this issue had been created 23 days ago since the last time you contact BohuTANG.
We are still busy developing the next alpha version, so we almost forgot to track the benchmarks with the latest version.

As you said, the store in datafuse is not ready, the benchmark with inconsistent conditions will be a little bit unfair and unfriendly, we will never do that again. 

But if you want to see the comparison between the latest versions of both, we'd like to send a text to you in private.  

Best wishes.
