### ISSUE TITLE
[improvement] use tls_server_cert/rpc_tls_server_key for RPC&HTTP tls

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#1303]
**Summary**

Use `tls_server_cert/rpc_tls_server_key` to instead of `rpc_tls_server_cert/rpc_tls_server_key` for all RPC&HTTP tls

cc @dantengsky

**Comment by dantengsky** [comment]
does it mean that we should use the same `server_cert/key` for both RPC and HTTP services?

**Comment by dantengsky** [comment]
Certs for https and rpc may be issued for different domain names (by different CAs)

**Comment by BohuTANG** [comment]
> does it mean that we should use the same `server_cert/key` for both RPC and HTTP services?

Now, we have:
https://github.com/datafuselabs/datafuse/blob/ad8b8f741c672ae4fad9737bb884744bc3b5a950/fusequery/query/src/configs/config.rs#L156-L175

Perhaps we can use `tls_server_cert/key` instead of `rpc_tls_server_cert/key`? Seems they are duplicated .
Domain is ok here.

**Comment by dantengsky** [comment]
I suggest keeping the cert/key separated, since 

- HTTPS services(and their REST protocol) are supposed to be publicly accessible, and they will bind to public IP address and domain name (latter in production env, with extra authen/author mechanism of course).
- On the contrary, RPC is supposed to be private inner-cluster(s) communication
- And AFAIK, while tonic TLS client negotiating with the TLS server, it does verify the domain name, which can not be disabled unless we modify some upstream dependency code (wrap or webpki, I forget it, unfortunately. based on versions of those crates months before), and also disabling the checking of domain name might not be a good option either.
- In test env, we can always configure them to be the same values, with extra two lines of config, we may avoid the aforementioned situation, it is not a bad deal I think. 

But,  names of `tls_server_cert` and `rpc_tls_server_cert`  may be confusing, if  that's what you are concerned, I suggest renaming the `tls_server_cert/key` to `https_server_cert/key`

**Comment by BohuTANG** [comment]
Ok.
We will change the name to `api_tls_server_cert/key`

**Comment by dantengsky** [comment]
got it
