### ISSUE TITLE
[development] install MySQL client in make setup

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#1337]
**Summary**
For stateless test while development, datafuse using MySQL client to do query, it would be better to install it in setup script.

**Comment by xxxinliActive** [comment]
Gonna pick this as a starter for my own.

It seems the `make setup` gonna support five major package managers and mysql-client are contained for most of them with one exception. Refer to the [MySQL - ArchWiki](https://wiki.archlinux.org/title/MySQL), the support for mysql was dropped due to their policies. Based on this, which options we are in flavor of? AUR community maintained builds, pre-built binaries or source build from scratch?

**Comment by PsiACE** [comment]
> AUR community maintained builds, pre-built binaries or source build from scratch?

aur or pre-built binary would be nice and maybe it is necessary to give users a hint.
