### ISSUE TITLE
Concerns about the raft log index

### ISSUE THREAD

**Issue by danielgatis** [datafuselabs/datafuse#1632]
Hi,

I have a question about the index of the log. Is it correct to start from`0`?
https://github.com/datafuselabs/datafuse/blob/master/store/src/meta_service/raftmeta.rs#L457

following these instructions https://github.com/datafuse-extras/async-raft/blob/master/raft-essentials.md#can-the-log-index-reset-per-term, shouldn't it be the `last snapshot index` up to the `current snapshot index`?

**Comment by drmingdrmer** [comment]
Hi,

Every time a snapshot is built, either by building it locally with `do_log_compaction()`, or installing a snapshot received from another leader with `finalize_snapshot_installation()`, the log entries that are included in the snapshot is removed.

That's why it just removes all entries from the beginning up to current snapshot index.

A snapshot only contains applied entries, and an applied entry can only be a committed one.
By the definition of `commit`, there will be never a conflict with a committed entry.

The doc section you mentioned above is about how to optimize **uncommitted** log entries and irrelevant to these committed and applied entries.

**Comment by drmingdrmer** [comment]
> Is it correct to start from`0`?

Valid log index starts from `1`. Index 0 is only used in some uninitialized state, e.g. the initial `StateMachine.last_applied` is `LogId{term:0, index:0}`.

**Comment by danielgatis** [comment]
makes sense. tks.
