### ISSUE TITLE
[test] stddev function test not stable

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#1681]
**Summary**

```
[2021-09-01T05:12:05Z INFO  datafuse_store::api::rpc::flight_service] Receive do_action: GetDatabaseMeta(GetDatabaseMetaAction { ver_lower_bound: None })
01_0000_system_numbers:                                                 [ FAIL ] - result differs with:
--- /Users/runner/work/datafuse/datafuse/tests/suites/0_stateless/01_0000_system_numbers.result	2021-09-01 05:04:39.000000000 +0000
+++ /Users/runner/work/datafuse/datafuse/tests/suites/0_stateless/01_0000_system_numbers.stdout	2021-09-01 05:12:05.000000000 +0000
@@ -15,6 +15,6 @@
 100
 1
 true
-2886.751331514372
-2886.751331514372
-2886.751331514372
+2886.751331514368
+2886.751331514368
+2886.751331514368
```

**Comment by BohuTANG** [comment]
CC: @b41sh @sundy-li

**Comment by sundy-li** [comment]
Related to number floating computational error. But it's reasonable, it's unstable even in clickhouse.

```
pc :) set max_block_size = 10;

SET max_block_size = 10

Query id: b83c5b44-60dd-4018-933a-e14d4299a05c

Ok.

0 rows in set. Elapsed: 0.008 sec.

pc :) SELECT stddevPopStable(number) from numbers_mt(1000);

SELECT stddevPopStable(number)
FROM numbers_mt(1000)

Query id: ab42f2e0-bad3-41ff-b414-a4af8ecb0af5

┌─stddevPopStable(number)─┐
│       288.6749902572096 │
└─────────────────────────┘

1 rows in set. Elapsed: 0.010 sec. Processed 1.00 thousand rows, 8.00 KB (103.78 thousand rows/s., 830.22 KB/s.)

pc :) SELECT stddevPopStable(number) from numbers_mt(1000);

SELECT stddevPopStable(number)
FROM numbers_mt(1000)

Query id: e2e6a9e2-4735-4cd3-a02b-6661eabb7445

┌─stddevPopStable(number)─┐
│      288.67499025720946 │
└─────────────────────────┘

1 rows in set. Elapsed: 0.010 sec. Processed 1.00 thousand rows, 8.00 KB (102.70 thousand rows/s., 821.61 KB/s.)
```

**Comment by BohuTANG** [comment]
Ok, may be we should refine the test for it?

**Comment by b41sh** [comment]
I found that the result is related to the distribution of data blocks. When the data is not evenly distributed and some data blocks are empty, the result will be incorrect. Why are some data blocks empty? Is the data randomly distributed? @BohuTANG @sundy-li

**Comment by sundy-li** [comment]
>  Why are some data blocks empty

There's a method named `generate_parts` to distribute the parts,  I do not think it'll be an empty block if it works correctly.

>  Is the data randomly distributed

Yes, the parts are distributed into a global queue, the working threads will steal parts from this queue. 

If the max_threads is `4` and you select `select stdvarPop(number) from numbers(10)`.

There will be parts:

[2, 2, 2, 2, 2, 2]

There will many possible conditions of merges may happen:

1: 
Thread A: 2 +2 -> 4
                               + 2 -> 6
Thread B: 2 +2 -> 4
Thread C: 2 +2 -> 4
                              + 2 -> 6
Thread D:2 +2 -> 4

2.

Thread A: 2 +2 -> 4
                               + 2 -> 6
                                          + 2 - > 8         
Thread B: 2
Thread C: 2 +2 -> 4
                              + 2 -> 6
Thread D:2 +2 -> 4

3 ...


So the unstable results will happen because of floating accuracy.
```
  let t = (other.count as f64 / self.count as f64) * self.sum - other.sum;
   self.variance += other.variance
            + ((self.count as f64 / other.count as f64) / (self.count as f64 + other.count as f64))
                * t
                * t;
```

**Comment by b41sh** [comment]
The data is divided into n partition blocks and placed in a global queue, and n `AggregatorPartialTransform` threads are started to process each block separately, but in one thread, data blocks will be cyclically obtained from the global queue, so there may be a thread can obtain multiple blocks, while another thread doesn't obtain any block at all. In this case, some threads actually do nothing and are wasted. Since the row numbers of data processed by each thread are different each time, different intermediate results will be produced, resulting in different values in the final merge, which is the cause of unstable results.
Can we fix a thread to process only one data block at a time? because the number of data blocks and the number of threads are the same. This can ensure the stability of the calculation results, while not wasting unnecessary threads.
Another problem is that a fixed number of blocks will be used regardless of the amount of data. For some relatively small amounts of data, this is not necessary. We can dynamically determine the number of data blocks according to the amount of data.

**Comment by sundy-li** [comment]
> Can we fix a thread to process only one data block at a time

Yes, we can but it may not be efficient.

We have a setting named `max_block_size` to split the data into blocks. 

- If the block size goes too big, the block number for each thread will be smaller, thus if one thread works very slow on a large block,  other threads may not help.
- If the block size goes too small, there will be much more small blocks that will not work well in batch computes.

**Comment by b41sh** [comment]
Ok, I see, thanks for your explanation. @sundy-li

**Comment by sundy-li** [comment]
Another more, event we divide data into one block for each thread, like 4 threads each got [1,1,1,1] block with [4, 3, 3, 4] rows.
There will be varing  merge orders in the `AggregateFinalMerge` stage.
