### ISSUE TITLE
Type inference is wrong for number Literal

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/datafuse#323]
```
macbook-pro-2.local :) select toTypeName(33)

SELECT toTypeName(33)

Query id: 632494d8-3297-48a2-bb3a-714e05adcda2

┌─toTypeName(33)─┐
│ UInt64         │
└────────────────┘

1 rows in set. Elapsed: 0.004 sec.

```

Expect to have UInt8.

**Comment by BohuTANG** [comment]
Hi,

This due to the performance.

Suppose we coercion type to UInt8，for this query:
select max(number) from numbers_mt(100000000) group by number%3

For `number%3`:
left array type `number` is UInt64, and right scalar `8` is UInt8, so here:
https://github.com/datafuselabs/datafuse/blob/07eb15878e2c076200933d33ea9f07851752f598/common/datavalues/src/data_array_arithmetic.rs#L53

Coercion `8` type to UInt64, here is a performance drain, from my test, it's about ~50%.

For many cases of operations, same type always faster, thought they take up more bytes.

**Comment by sundy-li** [comment]
ClickHouse is using casting.

But I don't know how to reduce the performance drain.


Related codes 
```
void ActionsMatcher::visit(const ASTLiteral & literal, const ASTPtr & /* ast */,
    Data & data)
{
    DataTypePtr type = applyVisitor(FieldToDataType(), literal.value);
    const auto value = convertFieldToType(literal.value, *type);
...
}

```
DataTypePtr FieldToDataType::operator() (const UInt64 & x) const
{
    if (x <= std::numeric_limits<UInt8>::max()) return std::make_shared<DataTypeUInt8>();
    if (x <= std::numeric_limits<UInt16>::max()) return std::make_shared<DataTypeUInt16>();
    if (x <= std::numeric_limits<UInt32>::max()) return std::make_shared<DataTypeUInt32>();
    return std::make_shared<DataTypeUInt64>();
}

```

```

**Comment by BohuTANG** [comment]
The possible way is to only cast the data type for arrow::compute::cast.
For UInt8 to UInt64 type, we only change the data type for UInt8Array

**Comment by sundy-li** [comment]
Fixed in master.

```
datafuse :) select toTypeName(33)

SELECT toTypeName(33)

Query id: e6d6c78f-3810-4a1f-9b3b-91f132168d80

┌─toTypeName(33)─┐
│ UInt8          │
└────────────────┘

1 rows in set. Elapsed: 1.177 sec.

datafuse :)
datafuse :) select toTypeName(256)

SELECT toTypeName(256)

Query id: 3c4940ac-b3d9-416e-9881-289d6d205892

┌─toTypeName(256)─┐
│ UInt16          │
└─────────────────┘
```
