### ISSUE TITLE
[refactor] Generic aggregate functions

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/datafuse#644]
**Summary**
Currently, it needs a lot of work to add a custom aggregate function, like #642  

TODO:

- [x] Implement generic aggregate function from argument datatypes. This could remove lots of macros and matches which make the codes look much more clear and cleaner.
- [x] Add a guide doc for the developer to add a custom aggregate function. Maybe `how-to-add-aggregate-function.md`.

**Comment by JmPotato** [comment]
I'd like to help with this. But I don't have any ideas yet. It seems that if we want to reduce the use of macros, we need to determine the type of parameters in advance so that the redundant type checks could be removed. However, currently, the `common_datavalues::DataValue` we use to present data lacks association with `common_datavalues::DataType` or native type at the grammatical level, which needs the generic to be introduced.

Although I'm not familiar with the current code implementation, further digging is needed for me.😊

**Comment by sundy-li** [comment]
@JmPotato  That will be great if you can help with it.

>  However, currently, the common_datavalues::DataValue we use to present data lacks association with common_datavalues::DataType or native type at the grammatical level, which needs the generic to be introduced.

Yes, I have 2 points about this

1. Most aggregate functions are specialized by primitive types
2. We can use macros to build the association between types and values


Refer: https://github.com/ClickHouse/ClickHouse/blob/master/src/AggregateFunctions/Helpers.h#L41-L50

Feel free to contact me to discuss anything about it via WeChat (could be found in GitHub profile).

**Comment by sundy-li** [comment]
> However, currently, the common_datavalues::DataValue we use to present data lacks association with common_datavalues::DataType or native type at the grammatical level, which needs the generic to be introduced.

@JmPotato  Now, I am fully convince of that, I create an issue to track this #810
