### ISSUE TITLE
[testing] fuse-test: add tests for server handlers

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#723]
**Summary**

fuse-test default test is in MySQL protocol with:
https://github.com/datafuselabs/datafuse/blob/90cf20d79306afd4a88469c4464531edfc1b6011/tests/fuse-test#L438

We can improve it to test ClickHouse protocol handler.
This issue should be kick off after #717

**Comment by sundy-li** [comment]
It's hard to use clickhouse-client if the main goal for datafuse to be compatible with MySQL.

Because clickhouse-client will parse the SQL on client side, but some functions may not work through that.

Eg: 
1. `mysql` take  expression `add(1,3)` as column header `1 + 3`, while clickhouse take this as `plus(1, 3)`
2.  Create SQL like 

```
create table default.test_csv (id int,name varchar(255),rank int) Engine = CSV location = 'tests/data/sample.csv';
CREATE TABLE t(c1 int);
```
may not be accepted by `clickhouse-client`

3. `SELECT TRUE;` is not be accepted by `clickhouse-client`, because TRUE is not the keyword of clickhouse, but it works in MySQL
4.  ...

**Comment by BohuTANG** [comment]
Got, closed
